### ISSUE TITLE
Toggle Comment and Toggle Block Comment don't work

### ISSUE THREAD

**Issue by brandly** [munificent/wren-sublime#1]
Edit -> Comment -> Toggle Comment

cmd+/

**Comment by OdatNurd** [comment]
This doesn't work because the plugin doesn't include a file that tells sublime how to create such comments.

I assume @munificent doesn't care over much based on how long this issue has been open, but since Wren uses the same styles of comments as C/C++ does, the file [Comments (C++).tmPreferences](https://github.com/sublimehq/Packages/blob/master/C%2B%2B/Comments%20%28C%2B%2B%29.tmPreferences) file from the default Sublime C/C++ package, modified so that the scope setting is set to **source.wren** and dropped into a **Wren** folder in your package directory (``Preferences->Browse Packages) will resolve the issue.

**Comment by munificent** [comment]
> I assume @munificent doesn't care over much based on how long this issue has been open

I totally do care! I just missed this bug somehow. Too many open source projects! :)

> Wren uses the same styles of comments as C/C++ does, the file Comments (C++).tmPreferences file from the default Sublime C/C++ package, modified so that the scope setting is set to source.wren and dropped into a Wren folder in your package directory (``Preferences->Browse Packages) will resolve the issue.

Awesome. Unless someone wants to send me a pull request before I get to it, I'll try to get that done soon.

**Comment by OdatNurd** [comment]
Sweet! I didn't mean to impugn there, I was just surprised to notice how long that once had been by the wayside. I know how that goes! :)

As a side note, once the official package is updated, anyone that fixed the issue by doing what I mentioned above should remove the file that they added. It's essentially overriding the contents of the Wren package, and so if the official package ever makes a modification to this file, the version manually placed there will override any official changes.
